/*
* generated by Xtext
*/
package com.gwtarchetype.dsl.domainmodel.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class DomainModelOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
