/*
* generated by Xtext
*/
package com.gwtarchetype.dsl.domainmodel.ui.contentassist;

import com.gwtarchetype.dsl.domainmodel.ui.contentassist.AbstractDomainModelProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class DomainModelProposalProvider extends AbstractDomainModelProposalProvider {

}
